# Generated by Django 6.0.1 on 2026-02-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
